### ISSUE TITLE
I was hoping to be able to take a radius value as a message input

### ISSUE THREAD

**Issue by HarryHooper** [bartbutenaers/node-red-contrib-ui-heatmap#11]
Hi, I am rather new to node-red and I am loving this node, however I am designing a flexible heatmap interface where certain data inputs look much nicer with different radius values. I've been able to pass through msg.radius in the code and it updates when its redeployed, but I can't get it working when the message injected into the heatmap node is changed to show the change in msg.radius value.

**Comment by bartbutenaers** [comment]
Hi @HarryHooper,

This UI node is for the old Node-RED AngularJs dashboard, which is end of life.
Meanwhile a new dashboard D2 has been developed based on VueJs: see [here](https://dashboard.flowfuse.com/).
I hope to have finished this week the new version of this node, which will become a core node of the new dashboard.
If you are new to Node-RED I strongly suggest you to start using the new dashboard.
This old ui node is end of life, since I don't have enough free time to support two dashboards.

Kind regards,
Bart

**Comment by HarryHooper** [comment]
Thanks for letting me know, I'll keep an eye out!

**Comment by bartbutenaers** [comment]
For reference a link to the [pull request](https://github.com/FlowFuse/node-red-dashboard/pull/577) for anybody following this topic.
