### ISSUE TITLE
Deploy Error on the node.

### ISSUE THREAD

**Issue by RayMN** [bartbutenaers/node-red-contrib-ui-heatmap#2]
Hi Bart,
The error I'm getting in Node-Red on Deploy is: "TypeError: Cannot read property 'push' of undefined"

In the console I see:
```
TypeError: RED.require is not a function
    at new HeatMapNode (C:\Users\PWPRW01\.node-red\node_modules\node-red-contrib-ui-heatmap\heat_map.js:51:26)
    at createNode (C:\Users\PWPRW01\AppData\Roaming\npm\node_modules\node-red\red\runtime\nodes\flows\Flow.js:305:18)
    at Flow.start (C:\Users\PWPRW01\AppData\Roaming\npm\node_modules\node-red\red\runtime\nodes\flows\Flow.js:89:35)
    at start (C:\Users\PWPRW01\AppData\Roaming\npm\node_modules\node-red\red\runtime\nodes\flows\index.js:300:29)
    at C:\Users\PWPRW01\AppData\Roaming\npm\node_modules\node-red\red\runtime\nodes\flows\index.js:137:21
    at tryCatchReject (C:\Users\PWPRW01\AppData\Roaming\npm\node_modules\node-red\node_modules\when\lib\makePromise.js:845:30)
    at runContinuation1 (C:\Users\PWPRW01\AppData\Roaming\npm\node_modules\node-red\node_modules\when\lib\makePromise.js:804:4)
    at Fulfilled.when (C:\Users\PWPRW01\AppData\Roaming\npm\node_modules\node-red\node_modules\when\lib\makePromise.js:592:4)
    at Pending.run (C:\Users\PWPRW01\AppData\Roaming\npm\node_modules\node-red\node_modules\when\lib\makePromise.js:483:13)
    at Scheduler._drain (C:\Users\PWPRW01\AppData\Roaming\npm\node_modules\node-red\node_modules\when\lib\Scheduler.js:62:19)
29 Mar 06:32:45 - [error] [heat-map:e33e529f.a428b8] TypeError: Cannot read property 'push' of undefined
```
This occurs with the example code or if I replace the example heatmap node with a fresh one from the palette. I noticed that the one in the example has an output node and the one in the palette does not.
EDIT: Deployed via "Manage Palette"

**Comment by bartbutenaers** [comment]
Hi @rayMN,
the Node-RED dashboard supports custom widgets starting from version 2-10-0. Could it be that you are using an older version, because then it won't work.
I should add that on my readme file... 
Bart

**Comment by RayMN** [comment]
Hi @bartbutenaers 
I have now installed it on a Linux based system totally under my control
Node-Red = v0.19.2
node-red-dashboard = v2.14.0
node-red-contrib-heatmap = v1.1.2

I no long get errors during deployment, but the graphics never show up, and I have set the inject node to run every 5 seconds, places a debug node on the output of the array generator and it is showing random data arrays of the proper size.

The Heatmap UI Tab and Group shows up, but there is no Heatmap UI Element in the group.
Deployed using the cut and paste method, and the examples method, same results. I also built it from scratch from the palette with the same results.

![Heatmap](https://user-images.githubusercontent.com/10171295/55278634-ecc30f80-52dc-11e9-945b-f0a02258001f.png)
![Heatmap2](https://user-images.githubusercontent.com/10171295/55278635-ecc30f80-52dc-11e9-8565-d19a694973ff.png)

p.s. I have Node-Red in debug logging mode and there is no output errors for the deployment or during operations.

**Comment by bartbutenaers** [comment]
Hey @RayMN,
Could you please look at the browser console log, whether there are errors?  It might e.g. that (for some reason) the third party library console cannot be found.  
Thanks!
Bart

**Comment by RayMN** [comment]
A refresh of the page shown above gives this output in the browser console:
That was ugly ... how about an attached file.
[BrowserConsole.txt](https://github.com/bartbutenaers/node-red-contrib-ui-heatmap/files/3025796/BrowserConsole.txt)

**Comment by bartbutenaers** [comment]
Ray,
Is it possible to make a screenshot of the browser console?  The txt looks very weird on my pc ...

Your txt shows _**SyntaxError: expected expression, got '<'**_ ...
Had something alike while I was developing this node.
In my case that was caused by this scenario:
1. The widget tries to load the javascript library **heatmap.min.js** (from the Node-RED server)
2. When that file wasn't accessible, the widget received an **error page** (```<html>...```) instead of a javascript file.
3. Since the widget doesn't expect that first ```<``` character, I got a syntax error ...

So I 'assume' this might be something similar?  If that would be the case, then we would have to find out why the javascript file is not accessible in your case ...

In my case it works fine, which I can see (in Chrome) under the 'network' tab.  Indeed there you can see that the heatmap.min.js has been received without problems:

![image](https://user-images.githubusercontent.com/14224149/55282027-59212b80-533c-11e9-8bf2-3ab87de4f497.png)

Can you somewhere find something similar in your browser?  
When I copy the URL (from the above screenshot) into my browser's address bar, then I indeed see that the javascript library is loaded without problems:

![image](https://user-images.githubusercontent.com/14224149/55282129-60e1cf80-533e-11e9-9549-8a4eeeaecba2.png)

Thanks for your analysis !!!
Bart

**Comment by RayMN** [comment]
It is a 404 on the call to heatmap.min.js .... see below
![heatmapDebug](https://user-images.githubusercontent.com/10171295/55282227-0761ac80-530e-11e9-90f1-4ccf8dacecd4.png)

**Comment by RayMN** [comment]
I think this is the view you actually want ...
![Screenshot from 2019-03-30 17-06-46](https://user-images.githubusercontent.com/10171295/55282240-42fc7680-530e-11e9-9e7c-30513cf81ba0.png)

**Comment by bartbutenaers** [comment]
Yep, thanks!
In the [heatmap.js](https://github.com/bartbutenaers/node-red-contrib-ui-heatmap/blob/master/heat_map.js#L292) file, you can see the (server side) code which should handle the request and return the heatmap.min.js file.  But for some reason you never arrive there, or you arrive there but no file is returned.
Will need to think about that.  I have no out-of-the-box solution ...

**Comment by RayMN** [comment]
If it matters I'm running node on RHEL7 and CentOS 7 ... more than willing to do a screen share if you have good enough connection and want to look around.
They are virtual machines running on my Ubuntu desktop.

**Comment by bartbutenaers** [comment]
Thanks for the offer, but I think I will need to ask this on the Node-RED forum...
+ As you can see, the server side code handles all requests containing .../ui/heatmap/js/... in their url:
   ```
   RED.httpNode.get('/ui/heatmap/js/*' ....
   ```
+ And in my case the dashboard sends its request to http://.../ui/heatmap/js/heatmap.min.js, which means it matches the required pattern.
+ But in your case it http://.../dashboard/heatmap/js/heatmap.min.js which doesn't match, so it will never be redirected to my request handler...

That is as far as my knowledge goes ...

**Comment by RayMN** [comment]
I just went and found it .. it's located at:
[prw@RHEL-74-NR01 lib]$ pwd
/home/prw/.node-red/node_modules/node-red-contrib-ui-heatmap/lib
[prw@RHEL-74-NR01 lib]$ ll
total 32
-rw-r--r--. 1 prw prw 19582 Mar 22  2019 heatmap.js
-rw-r--r--. 1 prw prw  9454 Mar 22  2019 heatmap.min.js

on my machine.

**Comment by RayMN** [comment]
Ahhhhhhh ... I don't put by dashboard UI at /ui ... I use /dashboard ... that is in the settings.js file in .node-red for me 99.9% of the time I use node-red to build realtime dashboards for out IT systems. I want to change my default UI location back to /ui and see it that works.

**Comment by bartbutenaers** [comment]
Ok, good feedback!  We will have to find a solution to support setups like yours!  
My time is up for today...  See you tomorrow.

**Comment by RayMN** [comment]
That didn't really help. I have a different error but the problem of the element not showing up in the dashboard still exists. see image.

![Screenshot from 2019-03-30 17-41-31](https://user-images.githubusercontent.com/10171295/55282521-36c6e800-5313-11e9-920e-4c5e33a37627.png)

The error in the debugger now looks like this.

![Screenshot from 2019-03-30 17-44-32](https://user-images.githubusercontent.com/10171295/55282536-7ee60a80-5313-11e9-9deb-ca580b276581.png)

**Comment by bartbutenaers** [comment]
Hey Ray,
From your last screenshot I conclude that the library now has been loaded and cached (status **304**).  So that seems ok to me.  But you say you still don't see the widget.  I assume you have injected already a matrix of values in your last test, and refreshed the dashboard page?  Are there any errors in the '_**Console**_' tabsheet?

**Comment by RayMN** [comment]
That is correct, I did make sure there was data in the array, but if you look at the image above you see the Heatmap TAB and the Heatmap GROUP, but there is no Heatmap ELEMENT, like the gauges above it. Here is the console view from just now after a refresh of the Heatmap TAB.

![Screenshot from 2019-03-31 14-43-41](https://user-images.githubusercontent.com/10171295/55294209-b791ec80-53c4-11e9-8690-b6059c830e19.png)

Also, in case it's useful the Inspector view  for the same page refresh ...

![Screenshot from 2019-03-31 14-49-23](https://user-images.githubusercontent.com/10171295/55294221-d55f5180-53c4-11e9-97dc-bd0d85427b94.png)

**Comment by bartbutenaers** [comment]
Well my [html part](https://github.com/bartbutenaers/node-red-contrib-ui-heatmap/blob/master/heat_map.js#L29) isn't rocket science:
```
<div id="heatMapContainer_` + config.id + `" style="width:100%; height:100%;" ng-init='init(` + configAsJson + `)'></div>
<canvas id="heatMapLegend_` + config.id + `" style="width:100%; height:20px;" ng-show="config.showLegend" height="20px;">
```
And I can see in your screenshot that you have these both elements:
![image](https://user-images.githubusercontent.com/14224149/55294285-8d5e2000-5400-11e9-890b-34fe3b5385c8.png)

However as soon as the first message arrives in the dashboard, the heatmap library will create an extra canvas element (where the real heatmap will be drawed) as a child of the div element:
![image](https://user-images.githubusercontent.com/14224149/55294378-d793d100-5401-11e9-8f31-cda9a0e82871.png)

And that hasn't happened in your case for some reason ...
So just thinking out loud.  This is how it normally goes:
![image](https://user-images.githubusercontent.com/14224149/55294447-7ae4e600-5402-11e9-81b4-969e799dba1f.png)
+ As soon as a message arrives from the Node-RED flow, we will get at line 85.
+ When all conditions (from line 91) are fullfilled, the extra canvas element will be added to the div element (at line 97).

The only thing I can think of, is that not all conditions of line 92 are ok.  **_The length of the array (in the msg.payload) should be equal to the rows*columns product (see your node's config screen)_**.  But I assume that is true, because you have used my example flow ???

**Comment by RayMN** [comment]
I am using your example flow, so everything should be right with that. The array is 0-199 elements.
I still go back to the fact that there is nothing showing up in the dashboard Layout tab under Tabs & Links. Every other Dashboard element that I have ever used shows up there.

![Screenshot from 2019-03-31 15-42-53](https://user-images.githubusercontent.com/10171295/55294809-f7100700-53cb-11e9-959f-bd2a63cc5f1c.png)

If you will note the "New Gauges" Tab, it has 3 groups, each has one element. The Tab created for the Heatmap has a single group called Heatmap, but that group is empty. What is displaying below is an empty group on the ui page, I don't think the actual graphical element is being created at the time of deploy configuration. It should show up as a picture icon like the "Pair Horizontal" in the New Gauges Tab above.

![Screenshot from 2019-03-31 15-50-17](https://user-images.githubusercontent.com/10171295/55294872-b664bd80-53cc-11e9-940a-bb00016b499a.png)

**Comment by bartbutenaers** [comment]
Hey Ray,
I have checked in my own setup: indeed the node is **not** visible in the dashboard tree.  But it is visible in my dashboard (at the correct tab/group).  So I don't think that has something to do with it...

Meanwhile I have registered two questions in the Node-RED forum:
+ [custom-ui-node-not-visible-in-dashboard-sidebar](https://discourse.nodered.org/t/custom-ui-node-not-visible-in-dashboard-sidebar/9666)
+ [custom-ui-node-cannot-access-changed-path](https://discourse.nodered.org/t/custom-ui-node-cannot-access-changed-path/9667)

If you don't mind I'm going to try to fix those two issues first.  Don't think it has anything to do with the unvisible widget in your dashboard, but you never know ...  If it doesn't solve your case, I will need to debug your dashboard: the div element is available, and the heatmap library will add automatically a child canvas to the div (which doesn't happen in your case).  I have no clue why that fails at the moment, since it is a third-party library (and not my own code) ...

**Comment by RayMN** [comment]
That’s fine, I’m getting pulled in a different directions right now anyway for work. I will get back to it. Just let me know when you have something you want me to test. I may also build up a pristine environment and reinstall everything if I get some time. Will let you know if that makes a difference as well.

**Comment by bartbutenaers** [comment]
No hurry!  Work comes first ...
Got a lot of feedback in both Node-RED discussions and I have tried to fix them both.  
To test it, you can install my version directly from Github:
```
npm install bartbutenaers/node-red-contrib-ui-heatmap
```
So it should now appear in your dashboard tree view, and hopefully the library can be loaded without errors when using your custom 'dashboard' ui path.  But again, don't hurry !!

P.S. As you can see at the start of my [readme](https://github.com/bartbutenaers/node-red-contrib-ui-heatmap) page, this version contains my first Node-RED **breaking change**.  Very pitty, but cannot workaround it...  But good that you discovered the dashboard tree issue, because now at least they could change the documents and UI contribution sample code to avoid other developers making the same mistake...

**Comment by RayMN** [comment]
Hi Bart,
Just a quick update, I have installed from your git repository on my RHEL7 instance.
The heat map element does show up in the dashboard tree now, after removing the example node and replacing it with one from the pallet, also change the size settings to 20x10 in the node config and put it in the Heatmap tab.
I am currently still using the default /ui path and the heat map graphic is still not showing up, just the empty group like before.
So it looks like one down, one to go ... 

p.s. I still have not created a pristine environment to test in .. probably Saturday.

**Comment by RayMN** [comment]
Good news, I have created a fresh new install of Node-Red with the dashboard on Ubuntu and it's working as designed with your new version at both /ui and /dashboard. I'm now going to take one of my existing CentOS servers where it does not seem to work and remove and reinstall a fresh node-red and dashboard to see if that makes a difference. But at this point I think we can close the issue and (operator/confguration error) :) Thanks for working with me on this, if you need or want a tester in the future please feel free to reach out to me, wilsonprw at gmail should get to me just fine, or here on git, or the node-red slack channel.

**Comment by RayMN** [comment]
More good news, the RHEL 7 that was not working before is now working after deleting .node-red and restarting it. I did save my flow and settings files, replaced those and it all works fine.

**Comment by bartbutenaers** [comment]
Evening Ray,
That is indeed good news!  Thanks for all tests you have been doing.  And nice to hear that I have from now on my private heatmap test team ;-)
See you around,
Bart

**Comment by bartbutenaers** [comment]
P.S. Version **2.0.0** is now available on NPM
