### ISSUE TITLE
404 error on heatmap.min.js when ui path is /

### ISSUE THREAD

**Issue by remisarrailh** [bartbutenaers/node-red-contrib-ui-heatmap#3]
Got a 404 error on heatmap.min.js

settings.js
```
ui: { path: "/" }
```
Change this line to make a quick (but dirty fix)
```
RED.httpNode.get('/heatmap/js/*', function(req, res){
        var options = {
            root: __dirname + '/lib/',
            dotfiles: 'deny'
        };
```
I'll try to find a better way to make it works, when I understand a bit more how node-red works.

**Comment by bartbutenaers** [comment]
Hi Rémy,

Sorry for the delay!

When I was developing this node, we had a [discussion ](https://discourse.nodered.org/t/custom-ui-node-cannot-access-changed-path/9667/3) about this kind of issues on the Node-RED forum.

Normally this line is in comment in the settings.js file:
> // If you installed the optional node-red-dashboard you can set it's path
> // relative to httpRoot
> //ui: { path: "ui" },

But users can uncomment it, and change the path (which I **need to use** in my node!).  Since you have uncommented it and set it to ```/```, it indeed won't work (since I end up with 3 slashes in sequence ```///heatmap/js/*```)

Just out of curiosity: is there any reason why your path contains only ```/``` ?

I will try to create a fix this week.  Would be nice if you could test it ...

Kind regards,
Bart

**Comment by bartbutenaers** [comment]
Hi Rémy (@maditnerd),

I have fixed this on Github.
You can install this version from Github directly (in your Node-RED folder):
```
npm install bartbutenaers/node-red-contrib-ui-heatmap
```
Would be nice if you could test whether it works now.
If it is OK, I will publish it on NPM.

Thanks!
Bart

**Comment by remisarrailh** [comment]
It works! Thanks a lot for the fix 👍

**Comment by bartbutenaers** [comment]
Version **2.1.1** has been published on NPM...
