### ISSUE TITLE
With 0 set as min and 1 as max a 0 in the array is red not blue

### ISSUE THREAD

**Issue by Dowster64** [bartbutenaers/node-red-contrib-ui-heatmap#6]
Hi,
I hope that the title is clear.
Array was set statically to: msg.payload=[0,.1,.2,.3,
             0.4,0,0,0,
             0,0,0,0,
             0,0,0,0,
             0,0,0,0,
             0,0,0,0,
             0,0,0,0,
             0,0,0,0];
Thanks,

Steve
![example heatmap](https://user-images.githubusercontent.com/13059464/114305588-1d6cef00-9b1c-11eb-8884-e971d0376894.PNG)

**Comment by bartbutenaers** [comment]
Hi Steve,
It seems that the heatmap.js library - which I use underneath - doesn't support decimals (see [here](https://github.com/pa7/heatmap.js/issues/260)).  And that library is not maintained anymore, so it will never be fixed...

The only workaround you can try: add a function node before the heatmap node, and multiply every number in your array with e.g. 100.  And optionally at the end round all numbers if you still have decimals.   Unfortunately I cannot give you an example flow, because I'm recovering from a surgery and I don't work on my computer these days...

Bart

**Comment by Dowster64** [comment]
Hi Bart,

Thanks for your quick reply, I’ll make up a work around.  Thanks for your suggestions and I hope that you recover soon,

Best Regards,

Steve

**Comment by bartbutenaers** [comment]
Hi @Dowster64,
I'm finally back...
Since I cannot solve this issue, I'm going to close it.  But I have added a paragraph on the readme page to inform users about the integer numbers, to make sure they don't get the same headache as you.
P.S. If you want to share the part of your flow where you convert your decimal numers to integer numbers, you can share it here in this issue so others can learn from it.
Kind regards,
Bart

**Comment by Dowster64** [comment]
Hi,
If this is useful, to scale individual values I used a change node with JSONata and used it to Set flow.heatmap[5] to:
$ceil(payload*1000)

*However*, if you want to apply the $ceil function to all the members of the heatmap array, it's a little more complicated.  You have to use the $map function like this:

$map(payload, function($v){$ceil($v*1000)})

This JSONata function rounds up and is applied to a flow variable called heatmap which is an array.  Personally I like JSONata, one could argue that it is just something more to learn, but I think it fits with the ethos of Node-RED as it is a query and transform language and great for modifying JSON formats.

I've added a simple flow to show the more complex $map in action

`[{"id":"e684afb.f1e6b5","type":"tab","label":"Array scaling test","disabled":false,"info":""},{"id":"74a2daf0.e6b084","type":"inject","z":"e684afb.f1e6b5","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[0,0.11111,0.22222,0.33333,0.44444,0.55555,0.66666,0.77777,0.88888,0.99999]","payloadType":"json","x":280,"y":120,"wires":[["1349023a.a369ee"]]},{"id":"1349023a.a369ee","type":"change","z":"e684afb.f1e6b5","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"$map(payload,function($v){$ceil($v*1000)})","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":460,"y":120,"wires":[["ff2d5e1d.808cc"]]},{"id":"ff2d5e1d.808cc","type":"debug","z":"e684afb.f1e6b5","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":700,"y":120,"wires":[]}]`

Steve

**Comment by bartbutenaers** [comment]
Hey Steve,
Thanks for the feedback!!!
Hopefully others can learn from it.
Nice use case for jsonata by the way...
Bart
